# Generated by Django 5.0.4 on 2024-09-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KunUzNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=1000, verbose_name='Link')),
                ('preview_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Preview link')),
                ('title', models.TextField(unique=True, verbose_name='Title')),
            ],
        ),
    ]
